baseURL = 'https://www.mitchman05.com/'
languageCode = 'en-us'
title = "Mitchell's Website"
theme = 'hello-friend-ng'

[params]
	dateform = "Jan 2, 2006"
	dateformShort = "Jan 2"
	dateformNum = "02-01-2006"
	dateformNumTime = "02-01-2006 15:04"

	homeSubtitle = "Dumbass website"

	disableReadOtherPosts = true

	enableSharingButtons = false

[languages]
	[languages.en]
		title = "Test title"
		keywords = ""
		copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menus]
	[[menus.main]]
		name = "Home"
		pageRef = "/"
		weight = 10
	[[menus.main]]
		name = "About"
		pageRef = "/about"
		weight = 20
	[[menus.main]]
		name = "Posts"
		pageRef = "/posts"
		weight = 20
